# Generated by Django 3.2.5 on 2023-01-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ereciept', '0002_auto_20230124_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='enviroment',
            field=models.CharField(blank=True, choices=[('production', 'production'), ('preproduction', 'preproduction')], default='preproduction', max_length=80, null=True),
        ),
    ]
