# Generated by Django 3.2.5 on 2023-02-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ereciept', '0003_seller_enviroment'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='pososversion',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
