# Generated by Django 3.2.5 on 2023-02-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ereciept', '0004_seller_pososversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiept',
            name='status',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='receiept',
            name='submitionid',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='receiept',
            name='t_uid',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
