# Generated by Django 3.2.5 on 2023-02-28 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ereciept', '0005_auto_20230226_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdata',
            name='taxtemplate',
        ),
        migrations.AddField(
            model_name='itemdata',
            name='taxtemplate',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='ereciept.taxtemplate'),
        ),
    ]
