# Generated by Django 3.2.5 on 2023-02-28 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ereciept', '0006_auto_20230228_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdata',
            name='taxtemplate',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='ereciept.taxtemplate'),
        ),
    ]
