# Generated by Django 3.2.5 on 2023-03-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ereciept', '0007_alter_itemdata_taxtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploader')),
            ],
        ),
    ]
