# Generated by Django 3.2.5 on 2023-03-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ereciept', '0008_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiept',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
    ]
