# Generated by Django 3.2.5 on 2023-03-07 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user_token', models.CharField(blank=True, max_length=100, null=True)),
                ('user_key', models.CharField(blank=True, max_length=100, null=True)),
                ('token_key', models.CharField(blank=True, max_length=100, null=True)),
                ('issuer_type', models.CharField(blank=True, max_length=100, null=True)),
                ('issuer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('issuer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('issuer_address_branchId', models.CharField(blank=True, max_length=100, null=True)),
                ('issuer_address_country', models.CharField(blank=True, max_length=100, null=True)),
                ('issuer_address_governate', models.CharField(blank=True, max_length=100, null=True)),
                ('issuer_address_regionCity', models.CharField(blank=True, max_length=100, null=True)),
                ('issuer_address_street', models.CharField(blank=True, max_length=100, null=True)),
                ('issuer_address_buildingNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('activty_number', models.CharField(blank=True, max_length=100, null=True)),
                ('documentTypeVersion', models.CharField(blank=True, choices=[('1.0', '1.0'), ('0.9', '0.9')], max_length=100, null=True)),
                ('environment', models.CharField(blank=True, choices=[('Production', 'Production'), ('Pre Production', 'Pre Production')], max_length=100, null=True)),
                ('lib', models.CharField(blank=True, default='C:/Windows/System32/eps2003csp11.dll', max_length=100, null=True)),
                ('token_label', models.CharField(blank=True, default='Egypt Trust', max_length=100, null=True)),
                ('user_pin', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
